### ISSUE TITLE
How do you assert an error was not raised?

### ISSUE THREAD

**Issue by StummeJ** [assertpy/assertpy#126]
Hi all, this is a great library but I cannot figure out how to assert an error was not raised.

**Comment by saturnboy** [comment]
@StummeJ I'm pretty sure that it is implicit is most testing that an error is not raised.  A passing test is *asserting* that an error was not raise.

If you really really want to guarantee via a test that `some_func()` does not raise an exception, you can do something like this: (also see [Failure](https://github.com/assertpy/assertpy#failure) in the readme)

```py
from assertpy import assert_that,fail

def test_exception_not_thrown():
    try:
        some_func('foo')  # might throw exception
    except RuntimeError as e:
        fail('doh! exception throw')
```

but honestly, this is not any different from this test:

```py
def test_exception_not_thrown():
    some_func('foo')  # might throw exception
```

**Comment by bbottema** [comment]
I disagree, because the first version explicitly states intention, while the second example works rather as a side effect. 

Because of this another developer might mistake the intention or add code before it that might also fail. Then it becomes more cumbersome to find out which statement caused it (go through the stacktrace, find the line), while with a 1st class assertion you would get proper reporting in the culprit.

And of course the first one is fine, but requires a lot of boilerplate code, which could be solved in a simple one liner.

**Comment by rmpinchback** [comment]
I also disagree.  One of the nice things about assertpy is that you can chain a described_as() for the error message.  When you're writing tests using pytest.mark.parametrize this combination makes for a very clean way to handle multiple cases of confirming lack-of-failure with a better message for what actually drove a failure.  Closing this issue was, I'd argue, considering the use case far too narrowly.
